resources:
 - ../generic-qmgr

generatorOptions:
 disableNameSuffixHash: true
# We use a configMapGenerator because it allows us to build up the mqsc from regular MQSC files.
configMapGenerator:
# Create an MQSC configMap using generic MQSC which will be added to all queue managers and applied during bootstrap.
- name: mqsc-configmap
  behavior: replace
  files:
  - ./static-definitions.mqsc
patchesStrategicMerge:
 - ./queuemanager.yaml
